version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Entrando na pasta do backend NestJS...
      - cd chatter-api
      - echo Habilitando o Corepack / Yarn...
      - corepack enable
      - echo Instalando dependencias com Yarn...
      - yarn install --frozen-lockfile

  build:
    commands:
      - echo Compilando a aplicacao NestJS...
      - yarn build

artifacts:
  base-directory: 'chatter-api'
  files:
    - 'dist/**/*'
    - 'package.json'
    - 'yarn.lock'
    - 'Procfile'
    - '.ebextensions/**/*'