version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd chatter-api
      - corepack enable
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build
      - rm -rf node_modules
      - mkdir -p node_modules
      - touch node_modules/.keep

artifacts:
  base-directory: 'chatter-api'
  files:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'package.json'
    - 'yarn.lock'
    - 'Procfile'
    - '.platform/**/*'