version: '3.8'
services:
  api:
    build:
      context: ./chatter-api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./chatter-api:/app
      - /app/node_modules
    env_file:
      - ./chatter-api/.env
    depends_on:
      - db

  client:
    build: 
      context: ./chatter-ui
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./chatter-ui:/app
      - /app/node_modules
    depends_on:
      - api

  db:
    image: mongo:6
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data: